import { IWorkingSettingPartResponse } from '@/models/workingSetting.model';

export const WORKING_SETTING_PART_RESPONSE: IWorkingSettingPartResponse[] = [
  {
    id: '1',
    position: '의사',
    positionColor: 'gray',
    tasks: '의사',
    division: '의사',
    isCertificated: true,
  },
  {
    id: '2',
    position: '간호사',
    positionColor: 'green',
    tasks: '간호사임',
    division: '일반',
    isCertificated: true,
  },
  {
    id: '3',
    position: '코디',
    positionColor: 'orange',
    tasks: '코디임',
    division: '일반',
    isCertificated: false,
  },
  {
    id: '4',
    position: '의사',
    positionColor: 'gray',
    tasks: '의사',
    division: '의사',
    isCertificated: true,
  },
  {
    id: '5',
    position: '조무사',
    positionColor: 'green',
    tasks: '조무사임',
    division: '일반',
    isCertificated: true,
  },
  {
    id: '6',
    position: '코디',
    positionColor: 'pink',
    tasks: '코디임',
    division: '일반',
    isCertificated: true,
  },
  {
    id: '7',
    position: '코디',
    positionColor: 'pink',
    tasks: '코디임',
    division: '일반',
    isCertificated: true,
  },
  {
    id: '8',
    position: '코디',
    positionColor: 'pink',
    tasks: '코디임',
    division: '일반',
    isCertificated: true,
  },
  {
    id: '9',
    position: '코디',
    positionColor: 'pink',
    tasks: '코디임',
    division: '일반',
    isCertificated: true,
  },
  {
    id: '10',
    position: '코디',
    positionColor: 'pink',
    tasks: '코디임',
    division: '일반',
    isCertificated: true,
  },
];
