import { IWorkingSettingPartResponse } from '@/models/workingSetting.model';

export const WORKING_SETTING_PART_RESPONSE: IWorkingSettingPartResponse[] = [
  {
    id: 1,
    name: '의사',
    task: '의사',
    is_doctor: true,
    required_certification: true,
    leave_granting_authority: true,
  },
  {
    id: 2,
    name: '간호사',
    task: '간호사임',
    is_doctor: true,
    required_certification: true,
    leave_granting_authority: true,
  },
  {
    id: 3,
    name: '코디',
    task: '코디임',
    is_doctor: false,
    required_certification: false,
    leave_granting_authority: true,
  },
  {
    id: 4,
    name: '의사',
    task: '의사',
    is_doctor: true,
    required_certification: true,
    leave_granting_authority: true,
  },
  {
    id: 5,
    name: '간호조무사',
    task: '조무사임',
    is_doctor: false,
    required_certification: true,
    leave_granting_authority: true,
  },
  {
    id: 6,
    name: '코디',
    task: '코디임',
    is_doctor: true,
    required_certification: true,
    leave_granting_authority: false,
  },
  {
    id: 7,
    name: '상담',
    task: '상담',
    is_doctor: true,
    required_certification: true,
    leave_granting_authority: false,
  },
  {
    id: 8,
    name: '코디',
    task: '코디임',
    is_doctor: true,
    required_certification: true,
    leave_granting_authority: true,
  },
  {
    id: 9,
    name: '코디',
    task: '코디임',
    is_doctor: true,
    required_certification: true,
    leave_granting_authority: false,
  },
  {
    id: 10,
    name: '코디',
    task: '코디임',
    is_doctor: true,
    required_certification: true,
    leave_granting_authority: true,
  },
];
