export const DATA = [
  {
    number: 2097,
    office: '뮤즈의원(안양점)',
    name: '김채은',
    part: '피부관리사',
    enroll_date: '2024-10-05',
    type: '재직증명서',
    status: '관리자 확인중',
    use: '은행 제출',
    memo: '',
    treat_date: '',
    applicant: '김채은',
  },
  {
    number: 2097,
    office: '뮤즈의원(안양점)',
    name: '김채은',
    part: '피부관리사',
    enroll_date: '2024-10-05',
    type: '재직증명서',
    status: '관리자 확인중',
    use: '은행 제출',
    memo: '',
    treat_date: '',
    applicant: '김채은',
  },
  {
    number: 2097,
    office: '뮤즈의원(안양점)',
    name: '김채은',
    part: '피부관리사',
    enroll_date: '2024-10-05',
    type: '재직증명서',
    status: '관리자 확인중',
    use: '은행 제출',
    memo: '',
    treat_date: '',
    applicant: '김채은',
  },
  {
    number: 2097,
    office: '뮤즈의원(안양점)',
    name: '김채은',
    part: '피부관리사',
    enroll_date: '2024-10-05',
    type: '재직증명서',
    status: '관리자 확인중',
    use: '은행 제출',
    memo: '',
    treat_date: '',
    applicant: '김채은',
  },
  {
    number: 2097,
    office: '뮤즈의원(안양점)',
    name: '김채은',
    part: '피부관리사',
    enroll_date: '2024-10-05',
    type: '재직증명서',
    status: '관리자 확인중',
    use: '은행 제출',
    memo: '',
    treat_date: '',
    applicant: '김채은',
  },
  {
    number: 2097,
    office: '뮤즈의원(안양점)',
    name: '김채은',
    part: '피부관리사',
    enroll_date: '2024-10-05',
    type: '재직증명서',
    status: '관리자 확인중',
    use: '은행 제출',
    memo: '',
    treat_date: '',
    applicant: '김채은',
  },
  {
    number: 2097,
    office: '뮤즈의원(안양점)',
    name: '김채은',
    part: '피부관리사',
    enroll_date: '2024-10-05',
    type: '재직증명서',
    status: '관리자 확인중',
    use: '은행 제출',
    memo: '',
    treat_date: '',
    applicant: '김채은',
  },
  {
    number: 2097,
    office: '뮤즈의원(안양점)',
    name: '김채은',
    part: '피부관리사',
    enroll_date: '2024-10-05',
    type: '재직증명서',
    status: '관리자 확인중',
    use: '은행 제출',
    memo: '',
    treat_date: '',
    applicant: '김채은',
  },
  {
    number: 2089,
    office: '뮤즈의원(광명점)',
    name: '신동수',
    part: '의사',
    enroll_date: '2024-7-11',
    type: '2024년 5월 급여명세서',
    status: '관리자 확인중',
    use: '서류제출용',
    memo: '',
    treat_date: '',
    applicant: '신동수',
  },
  {
    number: 2088,
    office: '뮤즈의원(광명점)',
    name: '신동수',
    part: '의사',
    enroll_date: '2024-07-11',
    type: '2024년 6월 급여명세서',
    status: '관리자 확인중',
    use: '서류제출용',
    memo: '',
    treat_date: '',
    applicant: '신동수',
  },
  {
    number: 2087,
    office: '샤인빔(강서)',
    name: '신현호',
    part: '의사',
    enroll_date: '2024-07-05',
    type: '2024년 갑종근로소득세 원천징수영수증',
    status: '관리자 확인중',
    use: '기관 제출용',
    memo: '',
    treat_date: '',
    applicant: '신현호',
  },
];
