export const TABLE_HEAD = [
  '번호',
  '지점',
  '이름',
  '근무파트',
  '신청날짜',
  '신청증명서',
  '상태',
  '용도',
  '관리자메모',
  '처리날짜',
  '담당자',
  '신청자',
  '',
];

export const TABLE_DATA = [
  {
    number: 2097,
    office: '뮤즈의원(안양점)',
    name: '김채은',
    part: '피부관리사',
    enroll_date: '2024-10-05',
    type: '재직증명서',
    status: '관리자 확인중',
    use: '은행 제출',
    memo: '',
    treat_date: '',
    manager: '',
    applicant: '김채은',
  },
  {
    number: 2096,
    office: '뮤즈의원(대전점)',
    name: '신수정',
    part: '마케터',
    enroll_date: '2024-09-23',
    type: '재직증명서',
    status: '관리자 확인중',
    use: '은행 제출',
    memo: '',
    treat_date: '',
    manager: '',
    applicant: '신수정',
  },
  {
    number: 2095,
    office: '샤인빔(포항)',
    name: '김민정',
    part: '피부관리사',
    enroll_date: '2024-09-20',
    type: '재직증명서',
    status: '관리자 확인중',
    use: '',
    memo: '',
    treat_date: '',
    manager: '',
    applicant: '김민정',
  },
  {
    number: 2094,
    office: '샤인빔(강서)',
    name: '최지수',
    part: '코디네이터',
    enroll_date: '2024-09-10',
    type: '재직증명서',
    status: '관리자 확인중',
    use: '은행 제출',
    memo: '',
    treat_date: '',
    manager: '',
    applicant: '최지수',
  },
  {
    number: 2093,
    office: '샤인빔(강서)',
    name: '김재환',
    part: '의사',
    enroll_date: '2024-08-12',
    type: '6월, 7월 급여명세서',
    status: '관리자 확인중',
    use: '은행 제출',
    memo: '',
    treat_date: '',
    manager: '',
    applicant: '김재환',
  },
  {
    number: 2092,
    office: '샤인빔(청주)',
    name: '강유선',
    part: '코디네이터',
    enroll_date: '2024-08-08',
    type: '원천징수영수증',
    status: '관리자 확인중',
    use: '2023년 원천징수영수증 2024년 원천징수영수증',
    memo: '',
    treat_date: '',
    manager: '',
    applicant: '강유선',
  },
  {
    number: 2091,
    office: '뮤즈의원(광명점)',
    name: '하민정',
    part: '총괄실장',
    enroll_date: '2024-07-22',
    type: '재직증명서',
    status: '관리자 확인중',
    use: '은행업무',
    memo: '',
    treat_date: '',
    manager: '',
    applicant: '하민정',
  },
  {
    number: 2090,
    office: '샤인빔(청주)',
    name: '조경옥',
    part: '피부관리사',
    enroll_date: '2024-07-11',
    type: '근로소득원천징수영수증(직인,최근2개년)',
    status: '관리자 확인중',
    use: '중도금',
    memo: '',
    treat_date: '',
    manager: '',
    applicant: '조경옥',
  },
  {
    number: 2089,
    office: '뮤즈의원(광명점)',
    name: '신동수',
    part: '의사',
    enroll_date: '2024-7-11',
    type: '2024년 5월 급여명세서',
    status: '관리자 확인중',
    use: '서류제출용',
    memo: '',
    treat_date: '',
    manager: '',
    applicant: '신동수',
  },
  {
    number: 2088,
    office: '뮤즈의원(광명점)',
    name: '신동수',
    part: '의사',
    enroll_date: '2024-07-11',
    type: '2024년 6월 급여명세서',
    status: '관리자 확인중',
    use: '서류제출용',
    memo: '',
    treat_date: '',
    manager: '',
    applicant: '신동수',
  },
  {
    number: 2087,
    office: '샤인빔(강서)',
    name: '신현호',
    part: '의사',
    enroll_date: '2024-07-05',
    type: '2024년 갑종근로소득세 원천징수영수증',
    status: '관리자 확인중',
    use: '기관 제출용',
    memo: '',
    treat_date: '',
    manager: '',
    applicant: '신현호',
  },
];
