// Mocks 폴더 만들기 좀 그래서 우선 constants에 넣었습니다.
import {
  IAttendance,
  ICommuteData,
  IDetailPartTimeData,
  IPartTimeData,
  IWorkData,
} from '@/models/work.model';

// 근로 관리
export const workMockData: IWorkData[] = [
  {
    id: 0,
    branch: '부산 클리어스킨 센터',
    name: '김영희',
    department: '간호사',
    workDate: 1,
    leaveDate: 0,
    regularDaysOff: 1,
    annualLeaveUsed: 2,
    unpaidLeaveUsed: 0,
    workFromHome: 1,
    holidayWork: 0,
    weekendWorkHours: 0,
    weekendWorkPay: 0,
    overtimeCount30min: 3,
    overtimeCount60min: 1,
    overtimeCount90min: 0,
    totalOvertime: 5000,
    gender: 0,
    days: 4,
  },
  {
    id: 1,
    branch: '부산 클리어스킨 센터',
    name: '김철수',
    department: '의사',
    workDate: 1,
    leaveDate: 0,
    regularDaysOff: 1,
    annualLeaveUsed: 2,
    unpaidLeaveUsed: 0,
    workFromHome: 1,
    holidayWork: 0,
    weekendWorkHours: 0,
    weekendWorkPay: 0,
    overtimeCount30min: 3,
    overtimeCount60min: 1,
    overtimeCount90min: 0,
    totalOvertime: 5000,

    gender: 1,
    days: 4,
  },
  {
    id: 2,
    branch: '대전 더마케어 클리닉',
    name: '김경택',
    department: '의사',
    workDate: 1,
    leaveDate: 0,
    regularDaysOff: 1,
    annualLeaveUsed: 2,
    unpaidLeaveUsed: 0,
    workFromHome: 1,
    holidayWork: 0,
    weekendWorkHours: 0,
    weekendWorkPay: 0,
    overtimeCount30min: 3,
    overtimeCount60min: 1,
    overtimeCount90min: 0,
    totalOvertime: 5000,

    gender: 1,
    days: 4,
  },
  {
    id: 3,
    branch: '서울 강남점',
    name: '김진영',
    department: '의사',
    workDate: 1,
    leaveDate: 0,
    regularDaysOff: 1,
    annualLeaveUsed: 2,
    unpaidLeaveUsed: 0,
    workFromHome: 1,
    holidayWork: 0,
    weekendWorkHours: 0,
    weekendWorkPay: 0,
    overtimeCount30min: 3,
    overtimeCount60min: 1,
    overtimeCount90min: 0,
    totalOvertime: 5000,

    gender: 0,
    days: 4,
  },
];
//백엔드 구조
export const mockAttendanceData: IAttendance[] = [
  {
    branch_name: '서울 본사',
    name: '김철수',
    gender: '남성',
    part_name: '개발팀',
    workdays: 22,
    leavedays: 1,
    regular_holiday: 8,
    annual_leave: 1,
    unpaid_use: 0,
    work_from_home: 5,
    weekend_work_hours: 4,
    holiday_work: 1,
    ot_30: 10,
    ot_60: 5,
    ot_90: 2,
    ot_total: 17,
  },
  {
    branch_name: '부산 지사',
    name: '이영희',
    gender: '여성',
    part_name: '마케팅팀',
    workdays: 21,
    leavedays: 2,
    regular_holiday: 8,
    annual_leave: 2,
    unpaid_use: 0,
    work_from_home: 3,
    weekend_work_hours: 0,
    holiday_work: 0,
    ot_30: 8,
    ot_60: 3,
    ot_90: 0,
    ot_total: 11,
  },
  {
    branch_name: '대전 지사',
    name: '박민수',
    gender: '남성',
    part_name: '인사팀',
    workdays: 20,
    leavedays: 3,
    regular_holiday: 8,
    annual_leave: 3,
    unpaid_use: 0,
    work_from_home: 1,
    weekend_work_hours: 6,
    holiday_work: 1,
    ot_30: 15,
    ot_60: 7,
    ot_90: 3,
    ot_total: 25,
  },
  {
    branch_name: '광주 지사',
    name: '최수진',
    gender: '여성',
    part_name: '영업팀',
    workdays: 23,
    leavedays: 0,
    regular_holiday: 8,
    annual_leave: 0,
    unpaid_use: 0,
    work_from_home: 2,
    weekend_work_hours: 8,
    holiday_work: 2,
    ot_30: 20,
    ot_60: 10,
    ot_90: 5,
    ot_total: 35,
  },
];

// 파트 관리
export const partTimeMockData: IPartTimeData[] = [
  {
    id: 1,
    branch: '서울지점',
    name: '김철수',
    workPart: '간호사',
    workDate: '2023-10-18',
    hospitalWork: '8시간',
    remoteWork: '0시간',
    holidayWork: '0시간',
    totalWorkHours: '8시간',
    totalSalary: '150,000원',
    workDetails: '정상근무',
    gender: '남자',
  },
  {
    id: 2,
    branch: '서울지점',
    name: '김철수',
    workPart: '간호사',
    workDate: '2023-10-18',
    hospitalWork: '8시간',
    remoteWork: '0시간',
    holidayWork: '0시간',
    totalWorkHours: '8시간',
    totalSalary: '150,000원',
    workDetails: '정상근무',
    gender: '남자',
  },
];

// 출퇴근 관리
export const commuteMockData: ICommuteData[] = [
  {
    id: 100,
    branch: '유즈의원(강남점)',
    name: '강동휘',
    gender: 1,
    position: '코디네이터',
    days: 5,
    schedule: {
      '1': { startTime: '10:24', endTime: '21:08', isHoliday: false },
      '2': { startTime: '10:39', endTime: '21:00', isHoliday: false },
      '3': { startTime: '21:08', endTime: '21:08', isHoliday: true },
      '4': { startTime: '20:30', endTime: '10:38', isHoliday: false },
      '5': { startTime: '09:00', endTime: '18:00', isHoliday: false },
    },
  },
  {
    id: 101,
    branch: '유즈의원(서초점)',
    name: '김미영',
    gender: 2,
    position: '간호사',
    days: 4,

    schedule: {
      '1': { startTime: '08:30', endTime: '17:30', isHoliday: false },
      '2': { startTime: '08:45', endTime: '17:45', isHoliday: false },
      '3': { startTime: '09:00', endTime: '18:00', isHoliday: false },
      '4': { startTime: '08:30', endTime: '17:30', isHoliday: false },
    },
  },
  {
    id: 102,
    branch: '유즈의원(강남점)',
    name: '박준서',
    gender: 1,
    position: '의사',
    days: 6,

    schedule: {
      '1': { startTime: '09:00', endTime: '18:00', isHoliday: false },
      '2': { startTime: '09:30', endTime: '18:30', isHoliday: false },
      '3': { startTime: '09:00', endTime: '18:00', isHoliday: false },
      '4': { startTime: '09:30', endTime: '18:30', isHoliday: false },
      '5': { startTime: '09:00', endTime: '18:00', isHoliday: false },
      '6': { startTime: '10:00', endTime: '15:00', isHoliday: false },
    },
  },
  {
    id: 103,
    branch: '유즈의원(서초점)',
    name: '이지은',
    gender: 2,
    position: '코디네이터',
    days: 5,

    schedule: {
      '1': { startTime: '00:00', endTime: '00:00', isHoliday: true },
      '2': { startTime: '00:00', endTime: '00:00', isHoliday: true },
      '3': { startTime: '00:00', endTime: '00:00', isHoliday: true },
      '4': { startTime: '00:00', endTime: '00:00', isHoliday: true },
      '5': { startTime: '00:00', endTime: '00:00', isHoliday: true },
    },
  },
];

export const detailPartTimeData: IDetailPartTimeData[] = [
  {
    id: 1,
    name: '김철수',
    date: '2023-10-18',
    department: '간호',
    workSection: '응급실',
    startTime: '09:00',
    endTime: '13:00',
    settingTime: '13:00-09:00',
    workHours: '4시간',
    breakTime: '30분',
    finalAmount: '50,000원',
    registrationDate: '2023-10-17',
  },
  {
    id: 2,
    name: '이영희',
    date: '2023-10-18',
    department: '간호',
    workSection: '응급실',
    startTime: '09:00',
    endTime: '13:00',
    settingTime: '13:00-09:00',
    workHours: '4시간',
    breakTime: '30분',
    finalAmount: '50,000원',
    registrationDate: '2023-10-17',
  },
  {
    id: 3,
    name: '박지민',
    date: '2023-10-18',
    department: '간호',
    workSection: '응급실',
    startTime: '09:00',
    endTime: '13:00',
    settingTime: '13:00-09:00',
    workHours: '4시간',
    breakTime: '30분',
    finalAmount: '50,000원',
    registrationDate: '2023-10-17',
  },
  {
    id: 4,
    name: '최유나',
    date: '2023-10-18',
    department: '간호',
    workSection: '응급실',
    startTime: '09:00',
    endTime: '13:00',
    settingTime: '13:00-09:00',
    workHours: '4시간',
    breakTime: '30분',
    finalAmount: '50,000원',
    registrationDate: '2023-10-17',
  },
];
