// Mocks 폴더 만들기 좀 그래서 우선 constants에 넣었습니다.
import { ICommuteData, IDetailPartTimeData, IPartTimeData, IWorkData } from '@/models/work.model';

// 근로 관리
export const workMockData: IWorkData[] = [
  {
    id: 0,
    branch: '서울 강남점',
    name: '김영희',
    department: '의사',
    workDate: 1,
    leaveDate: 0,
    regularDaysOff: 1,
    annualLeaveUsed: 2,
    unpaidLeaveUsed: 0,
    workFromHome: 1,
    holidayWork: 0,
    weekendWorkHours: 0,
    weekendWorkPay: 0,
    overtimeCount30min: 3,
    overtimeCount60min: 1,
    overtimeCount90min: 0,
    totalOvertime: 5000,
    gender: 0,
    days: 4,
  },
  {
    id: 1,
    branch: '서울 강남점',
    name: '김철수',
    department: '의사',
    workDate: 1,
    leaveDate: 0,
    regularDaysOff: 1,
    annualLeaveUsed: 2,
    unpaidLeaveUsed: 0,
    workFromHome: 1,
    holidayWork: 0,
    weekendWorkHours: 0,
    weekendWorkPay: 0,
    overtimeCount30min: 3,
    overtimeCount60min: 1,
    overtimeCount90min: 0,
    totalOvertime: 5000,

    gender: 1,
    days: 4,
  },
  {
    id: 2,
    branch: '서울 강남점',
    name: '김경택',
    department: '의사',
    workDate: 1,
    leaveDate: 0,
    regularDaysOff: 1,
    annualLeaveUsed: 2,
    unpaidLeaveUsed: 0,
    workFromHome: 1,
    holidayWork: 0,
    weekendWorkHours: 0,
    weekendWorkPay: 0,
    overtimeCount30min: 3,
    overtimeCount60min: 1,
    overtimeCount90min: 0,
    totalOvertime: 5000,

    gender: 1,
    days: 4,
  },
  {
    id: 3,
    branch: '서울 강남점',
    name: '김진영',
    department: '의사',
    workDate: 1,
    leaveDate: 0,
    regularDaysOff: 1,
    annualLeaveUsed: 2,
    unpaidLeaveUsed: 0,
    workFromHome: 1,
    holidayWork: 0,
    weekendWorkHours: 0,
    weekendWorkPay: 0,
    overtimeCount30min: 3,
    overtimeCount60min: 1,
    overtimeCount90min: 0,
    totalOvertime: 5000,

    gender: 0,
    days: 4,
  },
];
// 파트 관리
export const partTimeMockData: IPartTimeData[] = [
  {
    id: 1,
    branch: '서울지점',
    name: '김철수',
    workPart: '간호사',
    workDate: '2023-10-18',
    hospitalWork: '8시간',
    remoteWork: '0시간',
    holidayWork: '0시간',
    totalWorkHours: '8시간',
    totalSalary: '150,000원',
    workDetails: '정상근무',
    gender: 0,
  },
  {
    id: 2,
    branch: '서울지점',
    name: '김철수',
    workPart: '간호사',
    workDate: '2023-10-18',
    hospitalWork: '8시간',
    remoteWork: '0시간',
    holidayWork: '0시간',
    totalWorkHours: '8시간',
    totalSalary: '150,000원',
    workDetails: '정상근무',
    gender: 1,
  },
];

// 출퇴근 관리
export const commuteMockData: ICommuteData[] = [
  {
    id: 100,
    branch: '유즈의원(강남점)',
    name: '강동휘',
    gender: 1,
    position: '코디네이터',
    days: 5,
    isDayOff: false,
    schedule: {
      '1': { startTime: '10:24', endTime: '21:08', isDayOff: false },
      '2': { startTime: '10:39', endTime: '21:00', isDayOff: false },
      '3': { startTime: '21:08', endTime: '21:08', isDayOff: true },
      '4': { startTime: '20:30', endTime: '10:38', isDayOff: false },
      '5': { startTime: '09:00', endTime: '18:00', isDayOff: false },
    },
  },
  {
    id: 101,
    branch: '유즈의원(서초점)',
    name: '김미영',
    gender: 2,
    position: '간호사',
    days: 4,
    isDayOff: false,
    schedule: {
      '1': { startTime: '08:30', endTime: '17:30', isDayOff: false },
      '2': { startTime: '08:45', endTime: '17:45', isDayOff: false },
      '3': { startTime: '09:00', endTime: '18:00', isDayOff: false },
      '4': { startTime: '08:30', endTime: '17:30', isDayOff: false },
    },
  },
  {
    id: 102,
    branch: '유즈의원(강남점)',
    name: '박준서',
    gender: 1,
    position: '의사',
    days: 6,
    isDayOff: false,
    schedule: {
      '1': { startTime: '09:00', endTime: '18:00', isDayOff: false },
      '2': { startTime: '09:30', endTime: '18:30', isDayOff: false },
      '3': { startTime: '09:00', endTime: '18:00', isDayOff: false },
      '4': { startTime: '09:30', endTime: '18:30', isDayOff: false },
      '5': { startTime: '09:00', endTime: '18:00', isDayOff: false },
      '6': { startTime: '10:00', endTime: '15:00', isDayOff: false },
    },
  },
  {
    id: 103,
    branch: '유즈의원(서초점)',
    name: '이지은',
    gender: 2,
    position: '코디네이터',
    days: 5,
    isDayOff: true,
    schedule: {
      '1': { startTime: '00:00', endTime: '00:00', isDayOff: true },
      '2': { startTime: '00:00', endTime: '00:00', isDayOff: true },
      '3': { startTime: '00:00', endTime: '00:00', isDayOff: true },
      '4': { startTime: '00:00', endTime: '00:00', isDayOff: true },
      '5': { startTime: '00:00', endTime: '00:00', isDayOff: true },
    },
  },
];

export const detailPartTimeData: IDetailPartTimeData[] = [
  {
    id: 1,
    name: '김철수',
    date: '2023-10-18',
    department: '간호',
    workSection: '응급실',
    startTime: '09:00',
    endTime: '13:00',
    settingTime: '13:00-09:00',
    workHours: '4시간',
    breakTime: '30분',
    finalAmount: '50,000원',
    registrationDate: '2023-10-17',
  },
  {
    id: 2,
    name: '이영희',
    date: '2023-10-18',
    department: '간호',
    workSection: '응급실',
    startTime: '09:00',
    endTime: '13:00',
    settingTime: '13:00-09:00',
    workHours: '4시간',
    breakTime: '30분',
    finalAmount: '50,000원',
    registrationDate: '2023-10-17',
  },
  {
    id: 3,
    name: '박지민',
    date: '2023-10-18',
    department: '간호',
    workSection: '응급실',
    startTime: '09:00',
    endTime: '13:00',
    settingTime: '13:00-09:00',
    workHours: '4시간',
    breakTime: '30분',
    finalAmount: '50,000원',
    registrationDate: '2023-10-17',
  },
  {
    id: 4,
    name: '최유나',
    date: '2023-10-18',
    department: '간호',
    workSection: '응급실',
    startTime: '09:00',
    endTime: '13:00',
    settingTime: '13:00-09:00',
    workHours: '4시간',
    breakTime: '30분',
    finalAmount: '50,000원',
    registrationDate: '2023-10-17',
  },
];
